name: Android CI
on:
  push:
    branches: [master,updated_database,audio_notes_implemented]

jobs:
 build:
  runs-on: ubuntu-latest
  steps:
    - name: Checkout the code
      uses: actions/checkout@v2.3.4
    - name: Setup Java JDK
      uses: actions/setup-java@v2.0.0
      with: 
         java-version: 1.8
         distribution: 'adopt'
            
    - name: Build the app
      run: ./gradlew build
        
    - name: Upload APK
      uses: actions/upload-artifact@v2.2.3
      with:
       name: app
       key: app/build/outputs/apk/debug/app-debug.apk

