name: Android CI
on:
  push:
    branches: [master,updated_database,audio_notes_implemented]

jobs:
 build:
  runs-on: ubuntu-latest
  steps:
    - name: Checkout the code
      uses: actions/checkout@v2.3.4
            
    - name: Build the app
      run: ./gradlew build
        
   

