name: Android CI
on:
  push:
    branches: [master,updated_database,audio_notes_implemented]

jobs:
 build:
  runs-on: ubuntu-latest
  steps:
    - name: Checkout the code
      uses: actions/checkout@v2.3.4
            
    - name: Build the app
      run: ./gradlew build
  
    - name: Android Builder
  # You may pin to the exact commit or the version.
  # uses: b4s36t4/Android-Action@bb5c066db6ca0824ee09ee640ca222888a0c2877
      uses: b4s36t4/Android-Action@0.0.1
   

